### ISSUE TITLE
Pas très professionnel

### ISSUE THREAD

**Issue by cyrius** [cedricCaffy/ProjetAeroclub#2]
Bonjour, je vous conseille de revoir votre système de notation pour le COMMIT, en effet les message ne sont pas très pro. 
ex : TROP BELLES MES MAQUETTES !!

De plus certaines classes comme Avion ne possède pas de constructeur.

Je ne pense pas que créer une classe juste pour un enum soit intéressant (ex : Disponibilite).

La classe Espece n'apporte aucun nouveau comportement par rapport a sa classe mère donc elle est inutile.
Le fichier application.css est vide il n'est pas utile de le commit.
Le fichier coucou.txt ne devrait pas se trouver là, je conçoie que vous ne savez pas utiliser un environnement de travail "complexe" comme Github mais il serait bien d'effacer ce genre de fichiers quand ils ne servent plus.

Le projet devrait être séparé des autres dossiers comme UML ou BDD, vous pouvez envisager un sous dossier.

Cordialement Une personne qui vous veux du bien.

PS : Les cours sont obligatoires, si vous êtes malades vous ne travaillez pas sur votre projet.
PS2 : C'est tout pour le moment.

**Comment by cedricCaffy** [comment]
Corrigé dans un univers parallèle il y'a quelques années. Abandon du projet à la suite d'une note plus que convenable au projet ,ayant donné lieu à un diplôme bien mérité.
